# Generated by Django 5.0.6 on 2024-06-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_images_remove_category_image_remove_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
