# Generated by Django 5.0.6 on 2024-06-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_posts_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='category_id',
            new_name='category',
        ),
    ]
